<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN">
<!-- generated by to_html.pl from try.xml -->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>异常处理</title>
	<meta name="author" content="W.Dee" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link href="browser.css" type="text/css" rel="stylesheet" title="吉里吉里相关参考用标准样式" />
	<link href="mailto:dee@kikyou.info" rev="Made" />
	<link href="index.html" target="_top" rel="Start" title="首页" />
</head>
<body>
<h1><a id="id373" name="id373">异常处理</a>
</h1><div class="para"><div>
　<a id="id374" name="id374" class="targanchor"><dfn>异常</dfn></a>是指在通常处理中不会考虑到的情况，也就是所谓的"异常"，在大多数情况下可以理解为与"错误"相同。<br />
</div></div>
<h1><a id="id375" name="id375">异常发生的位置</a>
</h1><div class="para"><div>
　程序中的任何地方都可能发生异常。<br />
　触发异常也被称为"抛出(throw)异常"。<br />
　例如，假设以下脚本发生错误：<br />
<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;&quot;3%0&quot;!;&nbsp;<span class="comment">//&nbsp;发生"试图用0进行除法运算"异常</span></code>
<br />

<br />
　像这样，有些情况明显会发生异常，但也有些情况不确定是否会发生异常。<br />
</div></div>
<h1><a id="id376" name="id376">异常的捕获</a>
</h1><div class="para"><div>
　使用<code class="inlinecode"><a id="id377" name="id377" class="targanchor"><dfn>try</dfn></a></code>（尝试）关键字和<code class="inlinecode"><a id="id378" name="id378" class="targanchor"><dfn>catch</dfn></a></code>（捕获）关键字可以捕获异常。<br />
　例如，为了捕获上面例子中可能发生的异常，可以编写如下脚本：<br />
<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;<span class="comment">//&nbsp;可能会发生异常，所以</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;func1();&nbsp;<span class="comment">//&nbsp;这里可能会发生异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;<span class="comment">//&nbsp;捕获异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;发生异常时，这里会被执行</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inform(&quot;无法加载图像。&quot;);&nbsp;<span class="comment">//&nbsp;显示消息</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

<br />
　通过这种方式，在try块中编写可能发生异常的处理，当异常发生时可以执行catch块。这样可以简洁地编写错误处理代码。<br />
<br />
　如果try块中没有发生任何异常，则不会执行catch块。<br />
<br />
　try块中可以编写任何内容。就像这个例子一样，有时候确实可以明确某行代码可能会发生异常，但即使异常发生在函数调用的深层嵌套中，只要编写了try...catch，发生异常时也能返回到这里。<br />
<br />
　如果发生异常，块中剩余的处理将被中断，并返回到try所在的位置。<br />
<br />
　如果在catch块中又发生了异常，则在该位置不会捕获异常。异常会继续沿着函数调用栈回溯，如果在其他地方有try进行异常捕获，则会在那里被捕获。<br />
<br />
　从抛出异常到达达catch块之间可能会发生另一个异常，但这种情况下的行为是未定义的。<br />
<br />
　如果异常在脚本的任何地方都没有被捕获，异常将脱离脚本传递给应用程序，并在那里被处理。<br />
<br /><div class="note"><div class="notehead"><span class="noteheadspan">注</span></div>
通常，这类异常会作为错误中断执行，因此建议在可能发生错误的地方尽量编写try...catch。</div><br />
</div></div>
<h1><a id="id379" name="id379">异常对象</a>
</h1><div class="para"><div>
　与异常相关的各种信息会随<a id="id380" name="id380" class="targanchor"><dfn>Exception</dfn></a>类的对象一起被抛出。这个对象被称为异常对象。可以在catch中接收这个对象。<br />
　例如，可以编写如下脚本：<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;try<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loadImages(&quot;nothing.jpeg&quot;);&nbsp;<span class="comment">//&nbsp;可能会发生异常的处理</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(e)&nbsp;<span class="comment">//&nbsp;用变量e接收异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;e.message表示与异常一起抛出的消息字符串</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;这可能包含对异常发生原因的解释</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inform(&quot;无法加载图像。\n&quot;+e.message);<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

　这样，可以在catch后的括号中写入接收变量，并通过该变量接收异常对象。<br />
　这个变量的作用域从catch后的块开始，随着该块结束而结束。这个变量不需要事先声明。<br />
</div></div>
<h1><a id="id381" name="id381">throw语句</a>
</h1><div class="para"><div>
　也可以主动抛出异常。使用<code class="inlinecode"><a id="id382" name="id382" class="targanchor"><dfn>throw</dfn></a></code>关键字抛出异常。<br />
　例如，可以编写如下脚本：<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;function&nbsp;pow2(n)<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;计算2的n次方，n必须是正整数</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(n&lt;0)&nbsp;throw&nbsp;new&nbsp;Exception(&quot;不能指定负数。&quot;);<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;↑&nbsp;发生异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1&lt;&lt;n;<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

　如果该函数的参数传入了-1等负数，就会发生异常。抛出异常的是以下语句：<br />
<br />

<br />
<code class="bq">throw&nbsp;new&nbsp;Exception(&quot;不能指定负数。&quot;);</code>
<br />

<br />
　关于<code class="inlinecode">new Exception(&quot;不能指定负数。&quot;)</code>，这是使用字符串作为参数创建Exception类的对象。详情请参考Exception类。然后，通过throw关键字抛出这个新创建的对象。<br />
　throw关键字可以抛出的不仅限于Exception类的对象。也可以抛出数值、字符串，甚至对函数的引用。但是，建议抛出Exception类或从它派生的类的对象。这样在捕获时，catch块中只需要考虑处理Exception类的对象即可。<br />
</div></div>
<h1><a id="id383" name="id383">重新抛出异常</a>
</h1><div class="para"><div>
　虽然用catch捕获了异常，但可能在其他地方还有可以接收异常的try声明。在这种情况下，可以重新抛出异常。<br />
　可以编写如下脚本：<br />

<br />
<code class="bq"><span class="weak">例:</span><br />&nbsp;&nbsp;&nbsp;&nbsp;function&nbsp;tryloadimage()<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;primaryLayer.loadImages(&quot;test1.bmp&quot;);&nbsp;<span class="comment">//&nbsp;尝试读取test1.bmp</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch(e)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inform(&quot;图像加载失败。&quot;);<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;e;&nbsp;<span class="comment">//&nbsp;显示消息，但重新抛出异常</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;function&nbsp;test()<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;调用tryloadimage，如果图像加载成功则返回true</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="comment">//&nbsp;否则返回false的函数</span><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tryloadimage();<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;true;<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
</code>
<br />

　在这里调用test()函数，如果图像加载失败，inform方法会显示消息，但异常会被重新抛出，因此可以通过test函数内的catch捕获。<br />
</div></div>
	<script type="text/javascript" charset="UTF-8" src="documentid.js" ></script>
	<script type="text/javascript" charset="UTF-8" src="postcontent.js" ></script>
</body>
</html>
